spring:
  application:
    name: server

  ai:
    openai:
      api-key: ${OPEN_AI_API_KEY:VALID_OPENAI_API_KEY}
      embedding:
        dimensions: 1536
        model: text-embedding-3-small
      chat:
        model: gpt-4o-mini
    vectorstore:
      pgvector:
        dimensions: 1536 # Must perfectly match the dimensions configured above
        index-type: none
        distance-type: cosine_distance
        initialize-schema: true # Drops/creates schema on startup (vector_store table)

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/my_doc_companion}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mvc:
    apiversion:
      use:
        path-segment: 1

mycompanion:
  JWT_SECRET: ${MYCOMPANION_JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  REFRESH_TOKEN_SECRET: ${MYCOMPANION_REFRESH_TOKEN_SECRET:6B5970404E635266556A586E3272357538782F413F4428472B4B625064536756}
  ACCESS_TOKEN_VALIDITY: 3600000

logging:
  level:
    org.hibernate.SQL: debug
    root: info